INSERT INTO PRODUCTTABLE (NAME, PRICE) VALUES ('table', 1200);
INSERT INTO PRODUCTTABLE (NAME, PRICE) VALUES ('chair', 700);
INSERT INTO PRODUCTTABLE (NAME, PRICE) VALUES ('vase', 500);
INSERT INTO PRODUCTTABLE (NAME, PRICE) VALUES ('bed', 1500);
INSERT INTO PRODUCTTABLE (NAME, PRICE) VALUES ('mirror', 200);